language: node_js

node_js:
  - "4"
  - "6"

matrix:
  allow_failures:
   - node_js: "6"

addons:
  apt:
    packages:
      - dh-make
      - devscripts
      - debhelper
      - git

after_success:
 - ./node_modules/.bin/istanbul cover -x "**/spec/**" ./node_modules/.bin/_mocha --report lcovonly -- $(find spec -name '*-spec.js') -R spec --require spec/helper.js
 - cat ./coverage/lcov.info | node_modules/.bin/coveralls

before_deploy:
 - npm prune --production
 - mkdir -p packagebuild deb
 - cp -ar !(packagebuild) packagebuild/
 - pushd packagebuild
 - git log -n 1 --pretty=format:%h.%ai.%s > commitstring.txt
 - export DEBFULLNAME=`git log -n 1 --pretty=format:%an`
 - export DEBEMAIL=`git log -n 1 --pretty=format:%ae`
 - dch -l `echo "${TRAVIS_BRANCH}" | sed 's/[\/\_]/-/g'` -u low `git log -n 1 --pretty=oneline --abbrev-commit`
 - debuild --no-lintian --no-tgz-check -us -uc
 - popd
 - cp -a *.deb deb/

deploy: 
  provider: bintray
  file: .bintray.json
  user: $BINTRAY_USER
  key: $BINTRAY_KEY
  on:
    branch: master
    node: "0.10"

notifications:
  slack:
    rooms:
    - secure: "B57FLwzJ7lkHhccwWcojhyPgF1FnPkpG45ckzMAQYuyD/Te+dVrs5qY80xbEez4Kz2T1mOkOhZ4P7Vg9HpIbd7frD6kLOWGI2pXxjNMggJb9eLy3M+Dh/jOm2By6GRg6DEmNsedC0O9Y/CRsG++63kYRBJL04lIWl3PEY2wvGZC6bMrmoKseR6rvqkLQ4cLlWVucSRR01nSudsJjOdgSZF/Iz0D929LUhkHwo/AQQmZqFGJXnYv5No0EQ6WlvgS++eDH05gPfBjoJAQkdJZWX02YqDT9vQgx3HTcnkba/A3/o7aDecXXowqWyvTffDWXoAcfSNVjdFIgJkgZRcfsB/UKXcMNLIVT67kKircjg5TIHOQNqMv3PEsd7S6oDPqQlsOyVsoJzX8s/2zpc3nJnU2MtgatIqwtEifiE2S7tw+/3rrIUl+u5F40nr7OyIhiTH0LZRWILlRhy4MOsM/TBWfpHFOmebzW+dzfvHQ507ozdYVmx71ZzNMmQt08bnOuDnmN9eUG0s2AXefhiROnuCDzbFtWwFhswB/frtr3L9+Q5yh9Hp6sm6yGS+KJ2To5IusfJQCoWOQaMzLP6a7s1MeF8N/RDavcIMuwfB3SfUi4jvxDtoUpI9/DzlFihNaEEIvt+pFJHBFL7/5LD1NiMb88va8eHZorHTwJfkZ2Fow="
    on_success: never
    on_failure: always
    on_start: never
